/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kiecylhfsdcjeivhjhcq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZWN5bGhmc2RjamVpdmhqaGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxODg3MTksImV4cCI6MjEwNTc2NDcxOX0.HT_BFK6ELCKD9M-aBshMOZxe2dpLiHehKO-bvm1imUk"
